Filter out sandbox iframe from clone tree
1904labs/dom-to-image-more pull request #102
Opened 2023-01-11 10:47 UTC by meche-gh

Sometimes the sandbox iframe can appear in the clone.. if its in the DOM tree of `node` in `toSvg()` for example.
Let's make sure the iframe isn't cloned, just as an output linting + data saving measure.

NB: we *could* be thinking about sane defaults to filter `iframe` `script` `link` and `style`, but the developer can work around the issue(s) as they arise using `options.filter`.

2023-01-11 23:33 UTC, IDisposable commented
Instead of swapping `';'` for `'.'`, how about using a zero-width-space? `'\200B'` for this?

2023-01-12 03:00 UTC, IDisposable requested changes
Please review #103 which should replace this.

2023-01-12 08:45 UTC, meche-gh commented on src/dom-to-image-more.js
> +    // hoisted getDefaultStyle() variables
LGTM

2023-01-12 08:46 UTC, meche-gh commented on src/dom-to-image-more.js
> +        if (!root && (filter && !filter(node) || node === sandbox)) {
Go for it

2023-01-12 08:46 UTC, closed without merging